likelihood_estimator_config:
  name: 'double_langevin'
  config1:
    name: 'langevin'
    space: 'pixel'
    step: 100
    lr: 1e-4
    ode_step: 10
    tau: 0.01

  config2:
    name: 'langevin'
    space: 'latent'
    step: 50
    lr: 2e-6
    ode_step: 10
    tau: 0.01
    lr_scheduler: none
  t_cut: 0.5
  # num_steps = 30
  # timestep = double_poly-7-0.9-0.5-1

operator:
  name: gaussian_blur
  kernel_size: 61
  intensity: 3.0
  sigma: 0.05