likelihood_estimator_config:
  name: 'double_langevin'
  config1:
    name: 'langevin'
    space: 'pixel'
    step: 500
    lr: 1e-5
    ode_step: 20
    tau: 0.01
    lr_scheduler: sigma
  config2:
    name: 'langevin'
    space: 'latent'
    step: 100
    lr: 6e-7
    ode_step: 10
    tau: 0.01
    lr_scheduler: none
  t_cut: 0.9
  # num_steps = 30
  # timestep = double_poly-7-0.8-0.5-1'

operator:
  name: high_dynamic_range
  scale: 2
  sigma: 0.05