likelihood_estimator_config:
  name: 'langevin'
  step: 100
  lr: 1e-4
  ode_step: 10
  tau: 0.01

operator:
  name: inpainting
  mask_type: random  # box
  # mask_len_range: [128, 129]  # for box
  mask_prob_range: [ 0.70, 0.71 ]  # for random
  resolution: 256
  sigma: 0.05
