likelihood_estimator_config:
  name: 'double_langevin'
  config1:
    name: 'langevin'
    space: 'pixel'
    step: 100
    lr: 5e-5
    ode_step: 10
    tau: 0.01

  config2:
    name: 'langevin'
    space: 'latent'
    step: 20
    lr: 1e-6
    ode_step: 10
    tau: 0.01
    lr_scheduler: none
  t_cut: 0.9
  # num_steps = 30
  # timestep = double_poly-7-0.9-0.5-0.1

operator:
  name: inpainting
  mask_type: box  # box
  mask_len_range: [128, 129]  # for box
  # mask_prob_range: !!python/tuple [ 0.3, 0.7 ]  # for random
  resolution: 256
  sigma: 0.05
