likelihood_estimator_config:
  name: 'langevin'
  step: 100
  lr: 5e-5
  ode_step: 10
  tau: 0.01

operator:
  name: nonlinear_blur
  opt_yml_path: /home/bingliang/edm/bkse/options/generate_blur/default.yml
  sigma: 0.05