likelihood_estimator_config:
  name: 'double_langevin'
  config1:
    name: 'langevin'
    space: 'pixel'
    step: 100
    lr: 5e-5
    ode_step: 10
    tau: 0.01

  config2:
    name: 'langevin'
    space: 'latent'
    step: 100
    lr: 2e-6
    ode_step: 10
    tau: 0.01
    lr_scheduler: none
  t_cut: 0.5
  # num_steps = 30
  # timestep = double_poly-7-0.8-0.5-1'

operator:
  name: nonlinear_blur
  opt_yml_path: /home/bingliang/edm/bkse/options/generate_blur/default.yml
  sigma: 0.05