likelihood_estimator_config:
  name: 'double_langevin'
  config1:
    name: 'langevin'
    space: 'pixel'
    step: 500
    lr: 2e-5
    ode_step: 3
    tau: 0.01
    lr_scheduler: sigma
  config2:
    name: 'langevin'
    space: 'latent'
    step: 100
    lr: 4e-6
    ode_step: 3
    tau: 0.01
    lr_scheduler: none
  t_cut: 0.8

operator:
  name: phase_retrieval
  oversample: 2.0
  sigma: 0.05