likelihood_estimator_config:
  name: 'double_langevin'
  config1:
    name: 'langevin'
    space: 'pixel'
    step: 100
    lr: 1e-4
    ode_step: 2
    tau: 0.01

  config2:
    name: 'langevin'
    space: 'latent'
    step: 1
    lr: 1e-4
    ode_step: 2
    tau: 0.01

  t_cut: 0.9
  # num_steps = 30
  # timestep = double_poly-7-0.8-0.5-1'

operator:
  name: down_sampling
  resolution: 256
  scale_factor: 4
  sigma: 0.05
